### PR TITLE
fix: port typo

### PR DESCRIPTION
**Pull request by Cifko**
Description
---
Fix port typo. We want the default port for UI to be on port 5000.

### CODE REVIEW

**Review by sdbondi — APPROVED** [review]

**Comment by stringhandler** [comment]
Lol I preferred it on 15000

**Comment by sdbondi** [comment]
lol :) I agree with that - I was helping someone with weird HTTP denied errors which I thought might be because of port 5000 being in use on their machine.

**Comment by Cifko** [comment]
should we change the VN as well?

**Comment by stringhandler** [comment]
probably, but it should be a different port to the indexer

**Pull request closed without merging**
