### PR TITLE
chore: update rust to stable

### PR DESCRIPTION
**Pull request by sdbondi**
Description
---
Upgrade to stable rust

Motivation and Context
---
The nightly version we were using was older than the current stable rust.

How Has This Been Tested?
---
CI

What process can a PR reviewer use to test or verify this change?
---
N/A

Breaking Changes
---

- [x] None
- [ ] Requires data directory to be deleted
- [ ] Other - Please specify

### CODE REVIEW

**Review by jorgeantonio21 — DISMISSED** [review]
LGTM

It needs to run `cargo fmt` again, as the nightly version formatting is distinct from stable

**Comment by sdbondi** [comment]
@jorgeantonio21 ah well spotted - I'll update the fmt to use stable too

**Comment by sdbondi** [comment]
Lints are broken on nightly for some dependency of `log` and cargo fmt needs nightly features.

**Comment by sdbondi** [comment]
Updating `log` fixes the issue

**Review by stringhandler — APPROVED** [review]

**Pull request merged**
